# [Ctrl]+[Alt]+[R] で各セクションを実行

@service_id = 51mp4zpsjy
@api_key = DISS68MfXOKJjRSVeXHezAsz2QInNGuwSrZ0
@post_id = 4rwqm24v6sq

### 全投稿の取得
GET https://{{service_id}}.microcms.io/api/v1/posts
X-MICROCMS-API-KEY : {{api_key}}

### 単投稿の取得
GET https://{{service_id}}.microcms.io/api/v1/posts/{{post_id}}
X-MICROCMS-API-KEY : {{api_key}}